### PR TITLE
Use system prefix for impersonating serviceaccount

### PR DESCRIPTION
**Pull request by StrongMonkey**

### CODE REVIEW

**Comment by StrongMonkey** [comment]
From k8s docs:

> Service accounts authenticate with the username system:serviceaccount:(NAMESPACE):(SERVICEACCOUNT), and are assigned to the groups system:serviceaccounts and system:serviceaccounts:(NAMESPACE).

https://github.com/rancher/fleet/issues/372

**Review by nickgerace — APPROVED** [review]
LGTM, but should this be configurable?

**Comment by StrongMonkey** [comment]
@nickgerace Which part should be configurable? the serviceaccount is a top-level field from gitrepo and bundle.

**Comment by nickgerace** [comment]
@StrongMonkey curious if the prefix, including `system`, should be configurable.

**Review by kinarashah — APPROVED** [review]

**Comment by StrongMonkey** [comment]
@nickgerace Oh, I don't think that's configurable according to the docs.

**Pull request merged**
