### PR TITLE
Enhanced value substitution

### PR DESCRIPTION
**Pull request by gregsidelinger**
Add go template support for values substitution
Add support for cluster annotations and value substitution
Allow value substitution on values imported from configmaps and secrets

### CODE REVIEW

**Comment by nickgerace** [comment]
To reviewers: this is a parent PR to https://github.com/rancher/fleet/pull/507

**Comment by gregsidelinger** [comment]
I was doing a bunch of testing this weekend while migrating deployments over to fleet and ran into two issues with this code base. The first is a panic when calling the go template if you reference a undefined var.  I have a fix for this however I ran into this error on the fleet controller startup which I'm not sure how to fix.  It looks like the global section is not always set which I was relying upon to extra the fleet cluster labels from.



```
E0920 05:01:56.381702       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x2a5cc60), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x2aad940), missingMethod:""} (interface conversion: interface {} is nil, not map[string]interface {})
goroutine 1762 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x2b090a0, 0xc00457d500)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x2b090a0, 0xc00457d500)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/rancher/fleet/pkg/helmdeployer.(*helm).install(0xc004ec9f40, 0xc0001ed8f0, 0x11, 0xc0043e92c0, 0xc0043b3220, 0xc0001ed908, 0x13, 0x0, 0x0, 0xc00457aa50, ...)
	/go/src/github.com/rancher/fleet/pkg/helmdeployer/deployer.go:281 +0x12a7
github.com/rancher/fleet/pkg/helmdeployer.(*helm).Deploy(0xc004ec9f40, 0xc0001ed8f0, 0x11, 0xc0043e92c0, 0xc0001ed908, 0x13, 0x0, 0x0, 0xc00457aa50, 0xc003d07b90, ...)
	/go/src/github.com/rancher/fleet/pkg/helmdeployer/deployer.go:180 +0x325
github.com/rancher/fleet/pkg/helmdeployer.Template(0xc0001ed8f0, 0x11, 0xc0043e92c0, 0xc0001ed908, 0x13, 0x0, 0x0, 0x0, 0xc003d07b90, 0x0, ...)
	/go/src/github.com/rancher/fleet/pkg/helmdeployer/template.go:32 +0x1ff
github.com/rancher/fleet/pkg/controllers/bundle.setResourceKey(0xc004515e00, 0xc004540900, 0xc004eca8d8, 0x1, 0x1, 0x0)
	/go/src/github.com/rancher/fleet/pkg/controllers/bundle/controller.go:178 +0x658
github.com/rancher/fleet/pkg/controllers/bundle.(*handler).OnBundleChange(0xc00043aeb0, 0xc004540900, 0xc0043b98c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/fleet/pkg/controllers/bundle/controller.go:149 +0x1ce
github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1.(*bundleGeneratingHandler).Handle(0xc000ac5620, 0xc004540900, 0xc0043b98c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1/bundle.go:367 +0x136
github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1.(*bundleStatusHandler).sync(0xc0001a9620, 0xc001368820, 0x1d, 0xc0012038e0, 0x2e0b140, 0x2e97000, 0x33d8578)
	/go/src/github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1/bundle.go:307 +0x199
github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1.FromBundleHandlerToHandler.func1(0xc001368820, 0x1d, 0x3357ab0, 0xc0012038e0, 0xc0012038e0, 0x33d8578, 0xc0012038e0, 0x1)
	/go/src/github.com/rancher/fleet/pkg/generated/controllers/fleet.cattle.io/v1alpha1/bundle.go:105 +0x6b
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc0003957a0, 0xc001368820, 0x1d, 0x3357ab0, 0xc0012038e0, 0x0, 0xc0012038e0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x4e
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc000524700, 0xc001368820, 0x1d, 0x3357ab0, 0xc0012038e0, 0xc00340c401, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x14c
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc000952370, 0xc001368820, 0x1d, 0xc0007d71f8, 0x6c6e62304e6c4d)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xd1
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc000952370, 0x297ab80, 0xc000f49fa0, 0x0, 0x0)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xe7
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc000952370, 0x203001)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x54
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000c1c4f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000c1c4f0, 0x3341be0, 0xc00457c150, 0x6835475651526e01, 0xc0001ee6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000c1c4f0, 0x3b9aca00, 0x0, 0x5a746d4d436c3001, 0xc0001ee6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000c1c4f0, 0x3b9aca00, 0xc0001ee6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.21.3/pkg/util/wait/wait.go:90 +0x4d
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x33b
panic: interface conversion: interface {} is nil, not map[string]interface {} [recovered]
	panic: interface conversion: interface {} is nil, not map[string]interface {}
```

**Comment by gregsidelinger** [comment]
I've ported all features from this PR to #507 and think this PR should be abandoned as I'm not sure how to avoid the above exception that seems to happen when the global.fleet values are not present in the values data.  I only saw this on controller startup if the deployment was never fully processed but I'm not sure how to solve it unless I add clusterLabels and clusterAnnotations as parameters to the helmdeployer install function which will involve passing that data around to a lot of functions.  So based on that and my belief that adding substitution support to the configmaps and secrets present in the destination cluster is overkill I would say close this PR and focus on #507.

**Comment by SheilaghM** [comment]
Closing in favor of 507 and 528 per developer request.

**Pull request closed without merging**
