### PR TITLE
[WIP] Update gitjob to v0.1.17 and tekton utils to v0.1.2

### PR DESCRIPTION
**Pull request by nickgerace**
Relevant issue: https://github.com/rancher/fleet/issues/451

### CODE REVIEW

**Review by jiaqiluo — APPROVED** [review]
LGTM 
Before merging, can you make the deletion of v1beta1 API a separate commit?

**Comment by nickgerace** [comment]
@jiaqiluo keeping the one commit since we are not removing the GitJob CRD; we are updating it. Having said that, I updated the commit message to make it clear that apiext has been bumped for GitJob.

**Review by jiaqiluo — APPROVED** [review]

**Comment by nickgerace** [comment]
This is actually blocked by https://github.com/rancher/wrangler/pull/171. I had thought we could move it forward to open up the QA pipeline, but we will wait for Wrangler's update.

**Comment by nickgerace** [comment]
Closing since https://github.com/rancher/rancher/issues/33586 needs to be resolved, which will result in a new GitJob tag

**Pull request closed without merging**
