### PR TITLE
Add security context to token cleanup job

### LINKED ISSUE #1843: Cleanup job can't run because of missing security context
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The cluster registration cleanup job cannot run on clusters with a restricted security context. It is either blocked by podsecuritypolicies, or other mechanisms, as it's security context is empty and the container runs as root  per default.

As a result, one cannot update to the newest Fleet version, unless the `clusterRegistrationCleanup` value is set to `true`.

### Expected Behavior

The job runs (as the controller does) with a security context. It doesn't need extra permissions to run and do a simple cleanup.

### Steps To Reproduce

1. Have a k8s cluster with Gatekeeper / PSP still active and install Fleet 0.7.x
2. Upgrade Fleet to 0.8.0 with the cleanup option enabled
3. Upgrade won't happen because `fleet-cleanup-clusterregistrations` job cannot start

### Environment

```markdown
- Architecture: amd linux
- Fleet Version: 0.8.0
- Cluster:
  - Provider: rke
  - Options: 
  - Kubernetes Version: 1.24.x
```

### Logs

output of describe from job:
```
Name:             fleet-cleanup-clusterregistrations
Namespace:        cattle-fleet-system
Selector:         controller-uid=db6cb5f2-20e4-46c5-8a13-79c4586d8e75
Labels:           app=fleet-job
                  controller-uid=db6cb5f2-20e4-46c5-8a13-79c4586d8e75
                  job-name=fleet-cleanup-clusterregistrations
Annotations:      helm.sh/hook: post-install, post-upgrade
                  helm.sh/hook-delete-policy: hook-succeeded, before-hook-creation
Parallelism:      1
Completions:      1
Completion Mode:  NonIndexed
Start Time:       Fri, 06 Oct 2023 15:07:51 +0200
Pods Statuses:    0 Active (0 Ready) / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=fleet-job
                    controller-uid=db6cb5f2-20e4-46c5-8a13-79c4586d8e75
                    job-name=fleet-cleanup-clusterregistrations
  Service Account:  fleet-controller
  Containers:
   cleanup:
    Image:      mtr.devops.telekom.de/rancher/fleet-agent:v0.8.0
    Port:       <none>
    Host Port:  <none>
    Command:
      fleet
    Args:
      cleanup
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason            Age                  From            Message
  ----     ------            ----                 ----            -------
  Normal   SuccessfulCreate  13m                  job-controller  Created pod: fleet-cleanup-clusterregistrations-4lskv
  Warning  FailedCreate      10m (x4 over 11m)    job-controller  Error creating: pods "fleet-cleanup-clusterregistrations-" is forbidden: PodSecurityPolicy: unable to admit pod: []
```

### Anything else?

The job itself:
https://github.com/rancher/fleet/blob/master/charts/fleet/templates/job_cleanup_clusterregistrations.yaml

### PR DESCRIPTION
**Pull request by puffitos**
Fix #1843 

Adds a security context (like the one defined for the fleet-agent) to the cleanup job.

## Test

The cleanup job runs just fine. I wasn't able to get the e2e tests to run on my machine, so it's up to github :)

### Trade-off

None identified.

### Potential improvement

Maybe the possibility to define the securityContext for the containers in the helm chart would be meaningful, for use cases with restrictive security policies (like gatekeeper enforcing a complete security context for pods to run).

### CODE REVIEW

**Review by weyfonk — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by puffitos** [comment]
Glad to read that. We've already tested a similar scenario with a modified image, since changing the chart seemed tricky, given we roll out fleet with rancher.

We created a simple docker image based on the v0.0.8 one and just added `USER 1000`. It doesn't cover everything, but it runs perfectly in our hardened clusters. The cleanup job run without any problems fleet has been running fine as well (1 week in a cluster with around 30 GitRepos) 

Hope you get the same results!

**Review by raulcabello — APPROVED** [review]
LGTM,  thanks!

**Comment by manno** [comment]
Needs a backport to 0.9 to fix https://github.com/rancher/fleet/issues/1884

**Pull request merged**
