### PR TITLE
Secrets with vals

### PR DESCRIPTION
**Pull request by digiserg**
Please check out the [documentation attached](https://github.com/digitalis-io/fleet/blob/secretsWithVals/docs/secrets.md) describing this feature. This is a rewrite on #390

### CODE REVIEW

**Comment by digiserg** [comment]
In reply to https://github.com/rancher/fleet/pull/390#issuecomment-916352744 by @philomori, I'm afraid it won't work at the moment. The code will only work for *external* backends configured with environment variables.

**Comment by philomory** [comment]
@digiserg That's fine, maybe support for VALS+SOPS could be something added in a future enhancement. Having support for Vault, AWSSM, etc., is plenty right now.

**Comment by nickgerace** [comment]
It's on my list. We are getting a small, unplanned v0.3.7 release together for Rancher v2.6.1 at the moment. Thanks for you patience.

**Comment by philomory** [comment]
No problem, just wanted to make sure you'd seen it since I realized you hadn't actually been tagged in it yet.

**Comment by indstri** [comment]
This looks very promising and would be a big boon to have something native in Fleet for secrets to avoid more bolt on automation for pre-seeding.

I also like it's simplistic approach using vals for those that all ready have an external secret store.  Also love the upstream secret option.

I know our org would use this if implemented.

**Comment by digiserg** [comment]
Whilst we wait for this to be review and hopefully merged, we have put together an alternative in the form or an operator. This operator will keep your secrets in sync between any backend supported by vals and Kubernetes.

https://github.com/digitalis-io/vals-operator

**Comment by digiserg** [comment]
As an alternative to this pull request that it's taking very long to be reviewed, we have created this:

https://github.com/digitalis-io/vals-operator

**Comment by nickgerace** [comment]
Hi @digiserg - we've reviewed this internally and are going to think about this further as a new **feature** rather than the usual PRs we focus on externally: **bug fixes** and **enhancements**. As a result, I don't think @StrongMonkey or I will be merging this in the near future since we'd want to ensure we can get "net new" components approved (e.g. https://github.com/digitalis-io/vals-operator) as well as its implications for our QA team to provide coverage.

**_However_**, your effort into this PR, its documentation, etc. has not been unnoticed, and I would like for this idea to circulate through our internal product pipeline rather than be left fully out to dry. Thank you so much for the PR.

Due to the above, I've created a [new issue](https://github.com/rancher/fleet/issues/591) and marked it as a "Release Candidate" for those who help get us our work scheduled to take a look at. Admittedly, our SOPS, secret management story, etc. needs more attention and I can see that in [other places](https://github.com/rancher/fleet/pull/298). It's my hope that user and customer requests make their way to our product teams so that we add net new features from our community with relative ease.

Thank you for understanding, and I'm going to leave this PR open as a result with the issue attached as a result.

**Comment by digiserg** [comment]
Hi @nickgerace 

Thank you for the feedback and looking forward to seeing it as a feature in the future.

Regards

**Comment by nickgerace** [comment]
Not a problem @digiserg. I'm hoping we get the secrets story more hardened moving forward and we'll use that issue to track this one in particular.

**Comment by SheilaghM** [comment]
This needs to go through a design meeting before we merge.

**Comment by rajiteh** [comment]
Vals does look like a decent and a minimally intrusive solution to manage secret values at the controller level at the least. I found that pairing it with a template system allows a good amount of flexibility to pull in global secrets and cluster specific values if need be. I would be curious to see where the design heads towards. 

Please see my implementation on top of the templating feature that I have already proposed.

https://github.com/rancher/fleet/pull/671#issuecomment-1065397892
https://github.com/rajiteh/fleet/pull/3/files#diff-93aaee39046db788f486bd9059e637f612e0baeb27317f3a2c503e7f8da2e7f0R329

**Comment by endersonmenezes** [comment]
> This needs to go through a design meeting before we merge.

any news from this?

**Comment by kkaempf** [comment]
secrets handling is on our backlog but it'll take some time until we've review and consolidated all issues and PRs

> > This needs to go through a design meeting before we merge.
> 
> any news from this?

secrets handling is on our backlog but it'll take some time until we've review and consolidated all issues and PRs

**Comment by kkaempf** [comment]
> > any news from this?
> 
> secrets handling is on our backlog but it'll take some time until we've reviewed and consolidated all issues and PRs

**Comment by all4innov** [comment]
some updates on this issue ?

**Comment by areitz86** [comment]
would be interested as well

**Comment by alexdepalex** [comment]
Some updates on this issue? We would be interested as well :)

**Comment by manno** [comment]
We don't currently plan to implement support for specific operators that manage secrets.

If anyone is looking for examples, here is a [blog post about Fleet + External Secret Operator](https://www.suse.com/c/rancher_blog/fleet-multi-cluster-deployment-with-the-help-of-external-secrets/)

**Comment by willemm** [comment]
I looked at the example, and it is completely and utterly unusable for **bootstrapping** secrets.  Quote:

> We could use a Fleet bundle to distribute the secret to each downstream cluster, but we don’t want credentials outside of k8s secrets. So, we use kubectl on each cluster manually. 

The whole point of this, and similar, requests is to automate the creation of that first bootstrapping secret that is needed for the downstream cluster to do all the other secret-pulling stuff.

sops or sealedsecrets?  First you need to get the decryption key on the downstream cluster for the sops-operator
externalsecrets?  You'll need to get the credentials for externalsecrets to access the secrets vault

pushsecrets from the rancher cluster?  Now you need to manually add a pushsecret for each downstream cluster, thus negating all the benefits of fleet automatically targeting your newly provisioned cluster.

rancher/fleet can create secrets on downstream clusters just fine, all that is needed is for fleet to reference some secret provider to inject them. Even being able to access secrets that are on the upstream rancher-cluster would work just fine.

**Pull request closed without merging**
