### PR TITLE
[SURE-8456] fix: add owner reference to cluster registration request

### PR DESCRIPTION
**Pull request by pratikjagrut**
Refers to [SURE-8456](https://jira.suse.com/browse/SURE-8456)

This pull request adds the owner reference to cluster registration request

### CODE REVIEW

**Comment by manno** [comment]
From looking at related issues, like https://github.com/rancher/fleet/issues/478 and https://github.com/rancher/fleet/issues/1615 it seems clusterregistrations should be cleaned up.

The code at https://github.com/rancher/fleet/blob/main/internal/cmd/controller/agentmanagement/controllers/cluster/controller.go#L109-L134 is never executed. The handler doesn't trigger for delete events?

However regarding this PR:
* I would add the owner earlier, when OnChange created the cluster resource. At that point the cluster registration can be an owner.
* OnChange needs to update the request to actually store the owner, calling `SetOwnerReferences` is not enough.
* The [existing clean up code](https://github.com/rancher/fleet/blob/main/internal/cmd/controller/agentmanagement/controllers/cluster/controller.go#L109-L134) doesn't work, so it should also be removed. Or do we still need it for clusterregistrations that don't have a cluster yet?

**Comment by pratikjagrut** [comment]
> From looking at related issues, like #478 and #1615 it seems clusterregistrations should be cleaned up.
> 
> The code at https://github.com/rancher/fleet/blob/main/internal/cmd/controller/agentmanagement/controllers/cluster/controller.go#L109-L134 is never executed. The handler doesn't trigger for delete events?
> 
It's not deleting the cluster registration request.
> However regarding this PR:
> 
>  >   * I would add the owner earlier, when OnChange created the cluster resource. At that point the cluster registration can be an owner.
> 
> >    * OnChange needs to update the request to actually store the owner, calling `SetOwnerReferences` is not enough.
> 
> >    * The [existing clean up code](https://github.com/rancher/fleet/blob/main/internal/cmd/controller/agentmanagement/controllers/cluster/controller.go#L109-L134) doesn't work, so it should also be removed. Or do we still need it for clusterregistrations that don't have a cluster yet?

I updated the code as you suggested, but I'm still unable to test it, having some issues with the dev environment. As soon as I'm done testing I'll update it here.

**Comment by pratikjagrut** [comment]
@manno I tested the PR manually, and everything is working fine. Let me know if you need me to add tests to cover the changes.

**Comment by weyfonk** [comment]
> @manno I tested the PR manually, and everything is working fine. Let me know if you need me to add tests to cover the changes.

Would you mind expanding a bit on what has been tested, and results of those tests? :)

**Review by weyfonk — APPROVED** [review]
LGTM, thanks for your contribution :)

**Pull request merged**
